{
 "title": "Nextcloud",
 "tags": [
  "nextcloud",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nextcloud Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=\"nextcloud\"}) > bool 0"
    }
   ]
  },
  {
   "title": "Nextcloud CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"nextcloud\"}[5m]))"
    }
   ]
  },
  {
   "title": "Nextcloud RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"nextcloud\"}"
    }
   ]
  }
 ]
}